import{a as P,S as M,i}from"./assets/vendor-yGl9ZOHQ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();async function h(s,t=1){return(await P.get("https://pixabay.com/api/",{params:{key:"55981750-407047847782865d9c6ccfb62",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15}})).data}const f=document.querySelector(".gallery"),l=document.querySelector(".loader"),u=document.querySelector(".load-more"),$=new M(".gallery a",{captionsData:"alt",captionDelay:250});function y(s){const t=s.map(({webformatURL:a,largeImageURL:o,tags:e,likes:r,views:c,comments:v,downloads:q})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${o}">
        <img class="gallery-image" src="${a}" alt="${e}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b><span>${r}</span></p>
        <p class="info-item"><b>Views</b><span>${c}</span></p>
        <p class="info-item"><b>Comments</b><span>${v}</span></p>
        <p class="info-item"><b>Downloads</b><span>${q}</span></p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function B(){f&&(f.innerHTML="")}function L(){l&&l.classList.add("is-active")}function b(){l&&l.classList.remove("is-active")}function w(){u&&u.classList.remove("hidden")}function d(){u&&u.classList.add("hidden")}const m=document.querySelector(".form"),g=document.querySelector(".load-more");let p="",n=1;const S=15;m&&m.addEventListener("submit",E);g&&g.addEventListener("click",R);async function E(s){s.preventDefault();const t=s.currentTarget,a=t.elements["search-text"].value.trim();if(a===""){i.warning({title:"Caution",message:"Please enter a search query!",position:"topRight"});return}p=a,n=1,B(),d(),L();try{const o=await h(p,n);if(o.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(o.hits);const e=Math.ceil(o.totalHits/S);n>=e?(d(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch(o){i.error({title:"Error",message:`Something went wrong: ${o.message}`,position:"topRight"})}finally{b(),t.reset()}}async function R(){n+=1,d(),L();try{const s=await h(p,n);y(s.hits);const t=document.querySelector(".gallery-item");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}const a=Math.ceil(s.totalHits/S);n>=a?(d(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch(s){i.error({title:"Error",message:`Something went wrong: ${s.message}`,position:"topRight"})}finally{b()}}
//# sourceMappingURL=index.js.map
